name: e_learning
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  video_player: ^2.9.5
  flutter_svg: ^2.0.17
  get_storage: ^2.1.1
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  chewie: ^1.10.0
  equatable: ^2.0.7
  http: ^1.3.0
  fl_chart: ^0.71.0  # ✅ moved correctly into main dependencies block
  cloudinary_public: ^0.23.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  file_picker: ^10.1.9
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - tools/images/
